FROM python:3.5
MAINTAINER https://github.com/sthysel/docker-youtube-dl

RUN groupadd -g __GID__ pirates
RUN useradd --uid __UID__ --gid __GID__ pirate

VOLUME /download
WORKDIR /download

RUN pip install --upgrade youtube_dl

USER pirate
ENTRYPOINT ["youtube-dl"]
CMD ["--help"]
